# Dataset directories
data_dir: 'data'
# train_dir: '/data/home/acw723/datasets/fma/fma_small'
train_dir: '/home/ivanmeresman-higgs/Documents/QueenMary/fma_small'
train_keys_dir: '/home/ivanmeresman-higgs/Documents/QueenMary/fma_small/fma_small_keys.npz'
train_beats_dir: '/home/ivanmeresman-higgs/Documents/QueenMary/fma_small/beats'
# train_dir: 'data/fma_small_all.json'
# val_dir: '/data/home/acw723/datasets/sample_100/audio'
val_dir: '/home/ivanmeresman-higgs/Documents/QueenMary/sample_100/htdemucs'
val_keys_dir: '/home/ivanmeresman-higgs/Documents/QueenMary/sample_100/sample_100_keys.npz'
# val_dir: '/data/home/acw723/datasets/fma/fma_medium'
# val_dir: 'data/fma_medium_all.json'
# ir_dir: '/data/home/acw723/datasets/ir'
ir_dir: '/home/ivanmeresman-higgs/Documents/QueenMary/ir'
# noise_dir: '/data/home/acw723/datasets/musan/noise/'
# noise_dir: '/data/home/eez083/sample_100_audio_wav/'
noise_dir: '/home/ivanmeresman-higgs/Documents/QueenMary/noise'

# train_dir: 'data/fma_small_all.json'
# val_dir: 'data/fma_medium_all.json'
# ir_dir: '/import/research_c4dm/ss380/AIR_1_4' # To-do: Change this
# noise_dir: '/import/c4dm-datasets/musan'


# Model input parameters
arch: 'grafp'
fs: 16000
dur: 5.0 # for sampleID it should probably be over 5 seconds
offset: 0.2
norm: 0.95
win_len: 1024
hop_len: 512
n_mels: 64
n_fft: 1024
n_peaks: 512  # max number of peaks to consider
silence: 0.0005  # silence threshold
blur_kernel: [7,7]  # blur kernel size

# Dataset and Model hyperparameters
train_sz: 8000
val_sz: 25000
bsz_train: 256
peak_stride: 2
n_filters : 8 # number of filters in the peak extraction layer
tau: 0.05
lr: 8.0e-5
min_lr: 7.0e-7
n_epochs: 400
T_max: 400
lambda: 0.0
error_threshold: 5

# stem: 'drums'

# SampleID train hyperparameters
mix_prob: 0.95
mix_gain_range: [0.05, 0.55]

# Augmentation hyperparameters
n_frames: 32 #10 #32 # depends on the spectrogram parameters (10 is for Music2latent)
overlap: 0.5
tr_snr: [0, 20]
val_snr: [0, 10]
test_snr: [19, 21]
time_mask: 8
freq_mask: 16
noise_prob: 1.0
ir_prob: 1.0

# Model architecture
d: 128
h: 1024
u: 32

# Database sizes (validation)
n_dummy: 100
n_query: 20